version: 0.0
os: linux
files:
  - source: target/some-service.jar
    destination: /home/ec2-user/service
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
